# Generated by Django 5.2.3 on 2025-07-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='gst',
            field=models.FloatField(default=18),
        ),
    ]
