# Generated by Django 5.2.3 on 2025-07-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_created_at_inventoryitem_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='Price',
            new_name='price',
        ),
    ]
