# Generated by Django 5.2.3 on 2025-07-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_bill_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='email',
        ),
    ]
