# Generated by Django 5.2.3 on 2025-07-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='billitem',
            name='gst',
            field=models.FloatField(default=0.0),
        ),
    ]
