# Generated by Django 5.2.3 on 2025-07-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_billitem_discount_billitem_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='gst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='gst_percentage',
            field=models.FloatField(default=18),
        ),
    ]
